name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker to Google Container Registry
        run: gcloud auth configure-docker gcr.io

      - name: Build the Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/herb-craft:latest .

      - name: Push the Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/herb-craft:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy herb-craft \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/herb-craft:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
